import { Playfair_Display } from 'next/font/google'
import './globals.css'

const inter = Playfair_Display({ weight: ['400','500','600','700','800','900'], subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#FFEAE3] bg-cover bg-center`}>
      {children}
      </body>
    </html>
  )
}
